# coding: utf-8

"""
    DNS DTC API

    The DNS DTC is a Universal DDI service providing load balanced DNS resolution.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from dtc.api.health_check_pdp_api import HealthCheckPdpApi

from universal_ddi_client.api_client import ApiClient


class TestHealthCheckPdpApi(unittest.TestCase):
    """HealthCheckPdpApi unit test stubs"""

    def setUp(self) -> None:
        api_instance = ApiClient()
        self.api = HealthCheckPdpApi(api_instance)

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        Create the PDPHealthCheck object.
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete the PDPHealthCheck object.
        """
        pass

    def test_list(self) -> None:
        """Test case for list

        Retrieve PDPHealthCheck objects.
        """
        pass

    def test_read(self) -> None:
        """Test case for read

        Retrieve the PDPHealthCheck object.
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update the PDPHealthCheck object.
        """
        pass


if __name__ == '__main__':
    unittest.main()
