# coding: utf-8

"""
    DNS DTC API

    The DNS DTC is a Universal DDI service providing load balanced DNS resolution.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from dtc.api.topology_api import TopologyApi

from universal_ddi_client.api_client import ApiClient


class TestTopologyApi(unittest.TestCase):
    """TopologyApi unit test stubs"""

    def setUp(self) -> None:
        api_instance = ApiClient()
        self.api = TopologyApi(api_instance)

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        Create the Topology object.
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete the Topology object.
        """
        pass

    def test_list(self) -> None:
        """Test case for list

        Retrieve Topology objects.
        """
        pass

    def test_read(self) -> None:
        """Test case for read

        Retrieve the Topology object.
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update the Topology object.
        """
        pass


if __name__ == '__main__':
    unittest.main()
