# coding: utf-8

"""
    DNS DTC API

    The DNS DTC is a BloxOne DDI service providing load balanced DNS resolution.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from dtc.api.health_check_icmp_api import HealthCheckIcmpApi

from universal_ddi_client.api_client import ApiClient


class TestHealthCheckIcmpApi(unittest.TestCase):
    """HealthCheckIcmpApi unit test stubs"""

    def setUp(self) -> None:
        api_instance = ApiClient()
        self.api = HealthCheckIcmpApi(api_instance)

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        Create the ICMPHealthCheck object.
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete the ICMPHealthCheck object.
        """
        pass

    def test_list(self) -> None:
        """Test case for list

        Retrieve ICMPHealthCheck objects.
        """
        pass

    def test_read(self) -> None:
        """Test case for read

        Retrieve the ICMPHealthCheck object.
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update the ICMPHealthCheck object.
        """
        pass


if __name__ == '__main__':
    unittest.main()
