# coding: utf-8

"""
    DNS DTC API

    The DNS DTC is a BloxOne DDI service providing load balanced DNS resolution.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from dtc.api.snmp_user_security_api import SnmpUserSecurityApi

from universal_ddi_client.api_client import ApiClient


class TestSnmpUserSecurityApi(unittest.TestCase):
    """SnmpUserSecurityApi unit test stubs"""

    def setUp(self) -> None:
        api_instance = ApiClient()
        self.api = SnmpUserSecurityApi(api_instance)

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        Create the SNMPUserSecurityModel object. Use this method to create a __SNMPUserSecurityModel__ object.
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete the SNMPUserSecurityModel object. Use this method to delete a __SNMPUserSecurityModel__ object.
        """
        pass

    def test_list(self) -> None:
        """Test case for list

        Retrieve SNMPUserSecurityModel objects. Use this method to retrieve __SNMPUserSecurityModel__ objects.
        """
        pass

    def test_read(self) -> None:
        """Test case for read

        Retrieve the SNMPUserSecurityModel object. Use this method to retrieve a __SNMPUserSecurityModel__ object.
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update the SNMPUserSecurityModel object. Use this method to update a __SNMPUserSecurityModel__ object.
        """
        pass


if __name__ == '__main__':
    unittest.main()
