# coding: utf-8

"""
    DNS DTC API

    The DNS DTC is a BloxOne DDI service providing load balanced DNS resolution.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from dtc.api.pool_api import PoolApi

from universal_ddi_client.api_client import ApiClient


class TestPoolApi(unittest.TestCase):
    """PoolApi unit test stubs"""

    def setUp(self) -> None:
        api_instance = ApiClient()
        self.api = PoolApi(api_instance)

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        Create the Pool object.
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete the Pool object.
        """
        pass

    def test_list(self) -> None:
        """Test case for list

        Retrieve Pool objects.
        """
        pass

    def test_read(self) -> None:
        """Test case for read

        Retrieve the Pool object.
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update the Pool object.
        """
        pass


if __name__ == '__main__':
    unittest.main()
