# coding: utf-8

"""
    DNS DTC API

    The DNS DTC is a Universal DDI service providing load balanced DNS resolution.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dtc.models.header_regex import HeaderRegex
from dtc.models.metadata import Metadata
from typing import Optional, Set
from typing_extensions import Self


class HTTPHealthCheck(BaseModel):
    """
    A __HTTPHealthCheck__ (_dtc/health_check_http_) represents a DTC __Server__ health check based on the Hypertext Transfer Protocol (HTTP).
    """ # noqa: E501
    check_response_body: Optional[StrictBool] = Field(
        default=None,
        description=
        "Optional. Flag which enables checking of the HTTP response body content. Defaults to _false_."
    )
    check_response_body_negative: Optional[StrictBool] = Field(
        default=None,
        description=
        "Optional. Flag which changes the meaning of the regex match result. If set to _true_, the response is valid if regular expression matches not found. Defaults to _false_.  The flag is currently not supported."
    )
    check_response_body_regex: Optional[StrictStr] = Field(
        default=None,
        description=
        "Optional. Regular expression to search for a string in the HTTP response body. Error if empty while _check_response_body_ is _true_. Defaults to empty."
    )
    check_response_header: Optional[StrictBool] = Field(
        default=None,
        description=
        "Optional. Flag which enables checking of the HTTP response header(s) content. Defaults to _false_."
    )
    check_response_header_negative: Optional[StrictBool] = Field(
        default=None,
        description=
        "Optional. Flag which changes the meaning of the header regexes match result. If set to _true_, neither expression matches must be found in their respective headers for the headers to be considered valid. Defaults to _false_."
    )
    check_response_header_regexes: Optional[List[HeaderRegex]] = Field(
        default=None,
        description=
        "Optional. List of (header, regular expression) pairs. All expression matches must be found in their respective headers for the headers to be considered valid. Error if empty while _check_response_header_ is _true_. Defaults to empty."
    )
    codes: Optional[StrictStr] = Field(
        default=None,
        description=
        "Optional. Response Status Codes meaning the health check is successful. If empty, any code means success. Individual codes and code ranges are supported, ex. \"102,105-107,109-110,120\"."
    )
    comment: Optional[StrictStr] = Field(
        default=None, description="Optional. Comment for __HTTPHealthCheck__.")
    disabled: Optional[StrictBool] = Field(
        default=None,
        description=
        "Optional. Flag which enables/disables __HTTPHealthCheck__. Defaults to _false_."
    )
    https: Optional[StrictBool] = Field(
        default=None,
        description=
        "Optional. Flag which enables Hypertext Transfer Protocol Secure (HTTPS) in a health check. Defaults to _false_."
    )
    id: Optional[StrictStr] = Field(default=None,
                                    description="The resource identifier.")
    interval: Optional[StrictInt] = Field(
        default=None,
        description=
        "Optional. Interval value in seconds. The health check runs only for the specified interval and it is measured from the beginning of the previous check cycle. Defaults to _15_."
    )
    metadata: Optional[Metadata] = Field(
        default=None,
        description=
        "Output only. __HTTPHealthCheck__ metadata. Defaults to empty object and should be explicitly requested using field selection."
    )
    name: StrictStr = Field(description="Display name of __HTTPHealthCheck__.")
    port: StrictInt = Field(
        description="Destination TCP port of __HTTPHealthCheck__.")
    request: Optional[StrictStr] = Field(
        default=None,
        description=
        "HTTP request in a text format, it consists of HTTP method, request target, HTTP headers, request body."
    )
    retry_down: Optional[StrictInt] = Field(
        default=None,
        description=
        "Optional. Retry down count. The value determines how many bad health checks in a row must be received by the onprem host from the DTC Server for treating the health check as failed. Defaults to _1_."
    )
    retry_up: Optional[StrictInt] = Field(
        default=None,
        description=
        "Optional. Retry up count. The value determines how many good health checks in a row must be received by the onprem host from the DTC Server for treating the health check as successful. Defaults to _1_."
    )
    tags: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional. The tags for __HTTPHealthCheck__ in JSON format."
    )
    timeout: Optional[StrictInt] = Field(
        default=None,
        description=
        "Optional. Timeout value in seconds. The health check waits for the specified number of seconds after sending a request. If it does not receive a response within the number of seconds, then the health check is considered as failed. Defaults to _10_."
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "check_response_body", "check_response_body_negative",
        "check_response_body_regex", "check_response_header",
        "check_response_header_negative", "check_response_header_regexes",
        "codes", "comment", "disabled", "https", "id", "interval", "metadata",
        "name", "port", "request", "retry_down", "retry_up", "tags", "timeout"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HTTPHealthCheck from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "id",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in check_response_header_regexes (list)
        _items = []
        if self.check_response_header_regexes:
            for _item in self.check_response_header_regexes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['check_response_header_regexes'] = _items
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HTTPHealthCheck from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "check_response_body":
            obj.get("check_response_body"),
            "check_response_body_negative":
            obj.get("check_response_body_negative"),
            "check_response_body_regex":
            obj.get("check_response_body_regex"),
            "check_response_header":
            obj.get("check_response_header"),
            "check_response_header_negative":
            obj.get("check_response_header_negative"),
            "check_response_header_regexes": [
                HeaderRegex.from_dict(_item)
                for _item in obj["check_response_header_regexes"]
            ]
            if obj.get("check_response_header_regexes") is not None else None,
            "codes":
            obj.get("codes"),
            "comment":
            obj.get("comment"),
            "disabled":
            obj.get("disabled"),
            "https":
            obj.get("https"),
            "id":
            obj.get("id"),
            "interval":
            obj.get("interval"),
            "metadata":
            Metadata.from_dict(obj["metadata"])
            if obj.get("metadata") is not None else None,
            "name":
            obj.get("name"),
            "port":
            obj.get("port"),
            "request":
            obj.get("request"),
            "retry_down":
            obj.get("retry_down"),
            "retry_up":
            obj.get("retry_up"),
            "tags":
            obj.get("tags"),
            "timeout":
            obj.get("timeout")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
