# coding: utf-8

"""
    DNS DTC API

    The DNS DTC is a Universal DDI service providing load balanced DNS resolution.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dtc.models.consolidated_health_check import ConsolidatedHealthCheck
from typing import Optional, Set
from typing_extensions import Self


class PoolHealthCheck(BaseModel):
    """
    A __PoolHealthCheck__ represents a link between __Pool__ and __HealthCheck__.
    """ # noqa: E501
    consolidated_health_check: Optional[ConsolidatedHealthCheck] = Field(
        default=None,
        description=
        "Optional. Consolidated health check configuration. When set, the DNS server running the named designator __DNS Service__ performs the health check on behalf of the __Pool__, and the result is shared with other DNS servers linked to the __Pool__ via __LBDN__ association. When unset, each DNS server performs the health check independently and no health status is shared."
    )
    health_check_id: StrictStr = Field(description="The resource identifier.")
    name: Optional[StrictStr] = Field(
        default=None, description="Display name of __HealthCheck__.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "consolidated_health_check", "health_check_id", "name"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PoolHealthCheck from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "name",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of consolidated_health_check
        if self.consolidated_health_check:
            _dict[
                'consolidated_health_check'] = self.consolidated_health_check.to_dict(
                )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PoolHealthCheck from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "consolidated_health_check":
            ConsolidatedHealthCheck.from_dict(obj["consolidated_health_check"])
            if obj.get("consolidated_health_check") is not None else None,
            "health_check_id":
            obj.get("health_check_id"),
            "name":
            obj.get("name")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
