# coding: utf-8

"""
    DNS DTC API

    The DNS DTC is a BloxOne DDI service providing load balanced DNS resolution.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dtc.models.metadata import Metadata
from dtc.models.pool_health_check import PoolHealthCheck
from dtc.models.pool_server import PoolServer
from dtc.models.ttl_inheritance import TTLInheritance
from typing import Optional, Set
from typing_extensions import Self


class Pool(BaseModel):
    """
    A __Pool__ (_dtc/pool_) represents a collection of servers, it is associated with a __Policy__ (_dtc/policy_).
    """ # noqa: E501
    comment: Optional[StrictStr] = Field(
        default=None, description="Optional. Comment for __Pool__.")
    disabled: Optional[StrictBool] = Field(
        default=None,
        description=
        "Optional. Flag which enables/disables __Pool__.  Defaults to _false_."
    )
    health_checks: Optional[List[PoolHealthCheck]] = Field(
        default=None,
        description=
        "Optional. List of __HealthCheck__ objects IDs assigned to __Pool__.  Defaults to _empty_."
    )
    id: Optional[StrictStr] = Field(default=None,
                                    description="The resource identifier.")
    inheritance_sources: Optional[TTLInheritance] = Field(
        default=None, description="Optional. The inheritance configuration.")
    metadata: Optional[Metadata] = Field(
        default=None,
        description=
        "Output only. __Pool__ metadata. Defaults to empty object and should be explicitly requested using field selection."
    )
    method: StrictStr = Field(
        description=
        "Load balancing method used for selecting __Server__ assigned to __Pool__.  Valid values are: * _round_robin_ If the _round_robin_ load balancing method is selected, BloxOne DDI adjusts the response to a query in a sequential and circular manner, directing clients to pools.  * _ratio_ If _ratio_ load balancing method is selected, BloxOne DDI adjusts the response to a query so that clients are directed to pool using weighted round robin, a load-balancing pattern in which requests are distributed among several resources based on weight assigned to each resource. The distribution of responses over time will be equal for all available pools but the sequence of the responses won't be guaranteed. When equal weights are assigned for resources (pools) it effectively leads to basic round robin which directs clients to pools in sequential and circular manner.  * _global_availability_ If _global_availability_ load balancing method is selected clients are directed to the first server that is up in the _servers_ list.  Defaults to _round_robin_."
    )
    name: StrictStr = Field(description="Display name of __Pool__.")
    pool_availability: Optional[StrictStr] = Field(
        default=None,
        description=
        "Optional. Pool Availability setting defines how __Pool__ health is calculated.  Valid values are: * _all_ If _all_ availability selected then __Pool__ is treated healthy when all pool's servers are healthy. * _quorum_ If _quorum_ availability selected then __Pool__ is treated healthy when at least N pool's servers are healthy. N is configurable via the value from _pool_servers_quorum_ setting. * _any_ If _any_ availability selected then __Pool__ is treated healthy when at least one pool's server is healthy.  Defaults to _any_."
    )
    pool_servers_quorum: Optional[StrictInt] = Field(
        default=None,
        description=
        "Pool Servers Quorum defines a minimal number of pool's healthy servers required for treating __Pool__ as healthy when Pool Availability is set to _quorum_."
    )
    server_availability: Optional[StrictStr] = Field(
        default=None,
        description=
        "Optional. Server Availability setting defines how __Server__ health is calculated.  Valid values are: * _all_ If _all_ availability selected then __Server__ is treated healthy when all pool's health checks are positive. * _quorum_ If _quorum_ availability selected then __Server__ is treated healthy when at least N pool's health checks are positive. N is configurable via the value from _server_health_checks_quorum_ setting. * _any_ If _any_ availability selected then __Server__ is treated healthy when at least one pool's health check is positive  Defaults to _all_."
    )
    server_health_checks_quorum: Optional[StrictInt] = Field(
        default=None,
        description=
        "Server Health Checks Quorum defines a minimal number of pool's positive health checks required for treating __Server__ as healthy when Server Availability is set to _quorum_."
    )
    servers: Optional[List[PoolServer]] = Field(
        default=None,
        description=
        "Optional. List of __Server__ objects assigned to __Pool__.  Defaults to _empty_."
    )
    tags: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional. The tags for __Pool__ in JSON format.")
    ttl: Optional[StrictInt] = Field(
        default=None,
        description=
        "Optional. Time to live value (in seconds) to be used for records in DTC response. Unsigned integer, min: 0, max 2147483647 (31-bits per RFC-2181)."
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "comment", "disabled", "health_checks", "id", "inheritance_sources",
        "metadata", "method", "name", "pool_availability",
        "pool_servers_quorum", "server_availability",
        "server_health_checks_quorum", "servers", "tags", "ttl"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Pool from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "id",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in health_checks (list)
        _items = []
        if self.health_checks:
            for _item in self.health_checks:
                if _item:
                    _items.append(_item.to_dict())
            _dict['health_checks'] = _items
        # override the default output from pydantic by calling `to_dict()` of inheritance_sources
        if self.inheritance_sources:
            _dict['inheritance_sources'] = self.inheritance_sources.to_dict()
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in servers (list)
        _items = []
        if self.servers:
            for _item in self.servers:
                if _item:
                    _items.append(_item.to_dict())
            _dict['servers'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Pool from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "comment":
            obj.get("comment"),
            "disabled":
            obj.get("disabled"),
            "health_checks": [
                PoolHealthCheck.from_dict(_item)
                for _item in obj["health_checks"]
            ] if obj.get("health_checks") is not None else None,
            "id":
            obj.get("id"),
            "inheritance_sources":
            TTLInheritance.from_dict(obj["inheritance_sources"])
            if obj.get("inheritance_sources") is not None else None,
            "metadata":
            Metadata.from_dict(obj["metadata"])
            if obj.get("metadata") is not None else None,
            "method":
            obj.get("method"),
            "name":
            obj.get("name"),
            "pool_availability":
            obj.get("pool_availability"),
            "pool_servers_quorum":
            obj.get("pool_servers_quorum"),
            "server_availability":
            obj.get("server_availability"),
            "server_health_checks_quorum":
            obj.get("server_health_checks_quorum"),
            "servers":
            [PoolServer.from_dict(_item) for _item in obj["servers"]]
            if obj.get("servers") is not None else None,
            "tags":
            obj.get("tags"),
            "ttl":
            obj.get("ttl")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
