# coding: utf-8

"""
    DNS DTC API

    The DNS DTC is a BloxOne DDI service providing load balanced DNS resolution.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dtc.models.metadata import Metadata
from dtc.models.record import Record
from typing import Optional, Set
from typing_extensions import Self


class Server(BaseModel):
    """
    An __Server__ (_dtc/server_) represents a target resource for load balancing.
    """ # noqa: E501
    address: Optional[StrictStr] = Field(
        default=None,
        description=
        "IP Address of the __Server__. Must be set to a valid IP address if __endpoint_type__ is set to __address__. Alternatively, it can be left blank."
    )
    auto_create_response_records: Optional[StrictBool] = Field(
        default=None,
        description=
        "Optional. If the flag is enabled, A, AAAA or CNAME __Record__ is automatically generated.  Defaults to _false_."
    )
    comment: Optional[StrictStr] = Field(
        default=None, description="Optional. Comment for __Server__.")
    disabled: Optional[StrictBool] = Field(
        default=None,
        description=
        "Optional. Flag which enables/disables __Server__.  Defaults to _false_."
    )
    endpoint_type: Optional[StrictStr] = Field(
        default=None,
        description=
        "The endpoint type configured for the __Server__. Can be IP Address or FQDN. The values of both fields __address__ and __fqdn__ are preserved and are not mutually exclusive, and the __endpoint_type__ defines which one to use.  Allowed values: * address * fqdn  Defaults to __address__."
    )
    fqdn: Optional[StrictStr] = Field(
        default=None,
        description=
        "Fully Qualified Domain name of the __Server__. Must be set to a valid FQDN if __endpoint_type__ is set to __fqdn__. Alternatively, it can be left blank."
    )
    id: Optional[StrictStr] = Field(default=None,
                                    description="The resource identifier.")
    metadata: Optional[Metadata] = Field(
        default=None,
        description=
        "Output only. __Server__ metadata. Defaults to empty object and should be explicitly requested using field selection."
    )
    name: StrictStr = Field(description="Display name of __Server__.")
    records: Optional[List[Record]] = Field(
        default=None,
        description="Optional. List of __Records__ of the __Server__.")
    tags: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional. The tags for __Server__ in JSON format.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "address", "auto_create_response_records", "comment", "disabled",
        "endpoint_type", "fqdn", "id", "metadata", "name", "records", "tags"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Server from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "id",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in records (list)
        _items = []
        if self.records:
            for _item in self.records:
                if _item:
                    _items.append(_item.to_dict())
            _dict['records'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Server from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address":
            obj.get("address"),
            "auto_create_response_records":
            obj.get("auto_create_response_records"),
            "comment":
            obj.get("comment"),
            "disabled":
            obj.get("disabled"),
            "endpoint_type":
            obj.get("endpoint_type"),
            "fqdn":
            obj.get("fqdn"),
            "id":
            obj.get("id"),
            "metadata":
            Metadata.from_dict(obj["metadata"])
            if obj.get("metadata") is not None else None,
            "name":
            obj.get("name"),
            "records": [Record.from_dict(_item) for _item in obj["records"]]
            if obj.get("records") is not None else None,
            "tags":
            obj.get("tags")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
