# coding: utf-8

"""
    DNS DTC API

    The DNS DTC is a Universal DDI service providing load balanced DNS resolution.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class SNMPUserSecurityModel(BaseModel):
    """
    Parameters for user-based security model of SNMPv3.
    """ # noqa: E501
    auth_passphrase: Optional[StrictStr] = Field(
        default=None,
        description=
        "User passphrase for authentication. Ignored for __NoAuth__, otherwise mandatory."
    )
    auth_protocol: Optional[StrictStr] = Field(
        default=None,
        description=
        "Authentication protocol.  Allowed values: * NoAuth * MD5 * SHA  Defaults to __NoAuth__."
    )
    id: Optional[StrictStr] = Field(default=None,
                                    description="The resource identifier.")
    privacy_passphrase: Optional[StrictStr] = Field(
        default=None,
        description=
        "User passphrase for privacy. Ignored for __NoPrivacy__, otherwise mandatory."
    )
    privacy_protocol: Optional[StrictStr] = Field(
        default=None,
        description=
        "Privacy protocol. Must be __NoPrivacy__ if auth_protocol set to __NoAuth__.  Allowed values: * NoPrivacy * DES * AES  Defaults to __NoPrivacy__."
    )
    username: Optional[StrictStr] = Field(
        default=None,
        description="User name with which to associate security information.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "auth_passphrase", "auth_protocol", "id", "privacy_passphrase",
        "privacy_protocol", "username"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SNMPUserSecurityModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "id",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SNMPUserSecurityModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "auth_passphrase":
            obj.get("auth_passphrase"),
            "auth_protocol":
            obj.get("auth_protocol"),
            "id":
            obj.get("id"),
            "privacy_passphrase":
            obj.get("privacy_passphrase"),
            "privacy_protocol":
            obj.get("privacy_protocol"),
            "username":
            obj.get("username")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
