# coding: utf-8

"""
    DNS DTC API

    The DNS DTC is a BloxOne DDI service providing load balanced DNS resolution.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dtc.models.metadata import Metadata
from typing import Optional, Set
from typing_extensions import Self


class TCPHealthCheck(BaseModel):
    """
    A __TCPHealthCheck__ (_dtc/health_check_tcp_) represents a DTC __Server__ health check based on the Transmission Control Protocol (TCP).
    """ # noqa: E501
    comment: Optional[StrictStr] = Field(
        default=None, description="Optional. Comment for __TCPHealthCheck__.")
    disabled: Optional[StrictBool] = Field(
        default=None,
        description=
        "Optional. Flag which enables/disables __TCPHealthCheck__. Defaults to _false_."
    )
    id: Optional[StrictStr] = Field(default=None,
                                    description="The resource identifier.")
    interval: Optional[StrictInt] = Field(
        default=None,
        description=
        "Optional. Interval value in seconds. The health check runs only for the specified interval and it is measured from the beginning of the previous check cycle. Defaults to _15_."
    )
    metadata: Optional[Metadata] = Field(
        default=None,
        description=
        "Output only. __TCPHealthCheck__ metadata. Defaults to empty object and should be explicitly requested using field selection."
    )
    name: StrictStr = Field(description="Display name of __TCPHealthCheck__.")
    port: StrictInt = Field(
        description="Destination TCP port of __TCPHealthCheck__.")
    retry_down: Optional[StrictInt] = Field(
        default=None,
        description=
        "Optional. Retry down count. The value determines how many bad health checks in a row must be received by the onprem host from the DTC Server for treating the health check as failed. Defaults to _1_."
    )
    retry_up: Optional[StrictInt] = Field(
        default=None,
        description=
        "Optional. Retry up count. The value determines how many good health checks in a row must be received by the onprem host from the DTC Server for treating the health check as successful. Defaults to _1_."
    )
    tags: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional. The tags for __TCPHealthCheck__ in JSON format."
    )
    timeout: Optional[StrictInt] = Field(
        default=None,
        description=
        "Optional. Timeout value in seconds. The health check waits for the specified number of seconds after sending a request. If it does not receive a response within the number of seconds, then the health check is considered as failed. Defaults to _10_."
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "comment", "disabled", "id", "interval", "metadata", "name", "port",
        "retry_down", "retry_up", "tags", "timeout"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TCPHealthCheck from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "id",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TCPHealthCheck from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "comment":
            obj.get("comment"),
            "disabled":
            obj.get("disabled"),
            "id":
            obj.get("id"),
            "interval":
            obj.get("interval"),
            "metadata":
            Metadata.from_dict(obj["metadata"])
            if obj.get("metadata") is not None else None,
            "name":
            obj.get("name"),
            "port":
            obj.get("port"),
            "retry_down":
            obj.get("retry_down"),
            "retry_up":
            obj.get("retry_up"),
            "tags":
            obj.get("tags"),
            "timeout":
            obj.get("timeout")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
