# coding: utf-8

"""
    DNS DTC API

    The DNS DTC is a Universal DDI service providing load balanced DNS resolution.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dtc.models.metadata import Metadata
from dtc.models.topology_rule_preset import TopologyRulePreset
from typing import Optional, Set
from typing_extensions import Self


class Topology(BaseModel):
    """
    A __Topology__ (_dtc/topology_) is a reusable, named set of __TopologyRulePreset__ objects that provide deterministic infrastructure classification for DTC __Policy__ evaluation using infrastructure source object tags.
    """ # noqa: E501
    comment: Optional[StrictStr] = Field(
        default=None, description="Optional. Comment for __Topology__.")
    disabled: Optional[StrictBool] = Field(
        default=None,
        description=
        "Optional. Flag which enables/disables __Topology__.  Defaults to _false_."
    )
    id: Optional[StrictStr] = Field(default=None,
                                    description="The resource identifier.")
    metadata: Optional[Metadata] = Field(
        default=None,
        description=
        "Output only. __Topology__ metadata. Defaults to empty object and should be explicitly requested using field selection."
    )
    name: StrictStr = Field(description="Display name of __Topology__.")
    rules: Optional[List[TopologyRulePreset]] = Field(
        default=None,
        description=
        "List of __TopologyRulePreset__ objects defining the resolving strategy for __Policy__. Preset names must be unique within __Topology__.  Defaults to a list with a single, default __TopologyRulePreset__."
    )
    tags: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional. The tags for __Topology__ in JSON format.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "comment", "disabled", "id", "metadata", "name", "rules", "tags"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Topology from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "id",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in rules (list)
        _items = []
        if self.rules:
            for _item in self.rules:
                if _item:
                    _items.append(_item.to_dict())
            _dict['rules'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Topology from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "comment":
            obj.get("comment"),
            "disabled":
            obj.get("disabled"),
            "id":
            obj.get("id"),
            "metadata":
            Metadata.from_dict(obj["metadata"])
            if obj.get("metadata") is not None else None,
            "name":
            obj.get("name"),
            "rules":
            [TopologyRulePreset.from_dict(_item) for _item in obj["rules"]]
            if obj.get("rules") is not None else None,
            "tags":
            obj.get("tags")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
