# coding: utf-8

"""
    DNS DTC API

    The DNS DTC is a Universal DDI service providing load balanced DNS resolution.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dtc.models.tag_rule import TagRule
from typing import Optional, Set
from typing_extensions import Self


class TopologyRule(BaseModel):
    """
    A __TopologyRule__ represents a rule for topology load balancing method.
    """ # noqa: E501
    code: Optional[StrictStr] = Field(
        default=None,
        description=
        "Optional. DNS code to return if rule matches. Must be set if _destination_ is set to _code_.  Allowed values: - nodata - nxdomain  Defaults to _nodata_."
    )
    destination: Optional[StrictStr] = Field(
        default=None,
        description=
        "Destination of __TopologyRule__.  Allowed values: - code - pool  Defaults to _code_."
    )
    name: StrictStr = Field(description="Display name of __TopologyRule__.")
    pool_id: Optional[StrictStr] = Field(
        default=None, description="The resource identifier.")
    source: Optional[StrictStr] = Field(
        default=None,
        description=
        "Type of source.  Allowed values: - subnet - tags - default  Defaults to _default_."
    )
    subnets: Optional[List[StrictStr]] = Field(
        default=None,
        description=
        "Optional. List of subnets in CIDR format.  Must be set if _source_ is _subnet_, otherwise must be empty."
    )
    tags: Optional[List[TagRule]] = Field(
        default=None,
        description=
        "Optional. List of tag rules to match against a source object's effective tags. Effective tags = direct tags plus tags inherited from the IPAM parent chain (IPSpace → Address Block → Subnet); the closer level wins on key conflicts. All rules use AND semantics: an object must satisfy every __TagRule__ to match.  Must be set if _source_ is _tags_, otherwise must be empty."
    )
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "code", "destination", "name", "pool_id", "source", "subnets", "tags"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TopologyRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item in self.tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tags'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TopologyRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code":
            obj.get("code"),
            "destination":
            obj.get("destination"),
            "name":
            obj.get("name"),
            "pool_id":
            obj.get("pool_id"),
            "source":
            obj.get("source"),
            "subnets":
            obj.get("subnets"),
            "tags":
            [TagRule.from_dict(_item)
             for _item in obj["tags"]] if obj.get("tags") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
